#' List generator
#'
#' This will generate lists with contents corresponding
#' to the values generated by the input generators.
#'
#' @param ... Generators
#'
#' @examples
#' list_(integer_(), logical_()) |> show_example()
#' list_(a = any_vector(), b = any_vector()) |> show_example()
#' @template generator
#' @export
list_ <- function(...) {
  hedgehog::gen.with(list(...), as.list)
}

#' Variable length list generator
#'
#' This will generate lists with all values coming from the
#' single input generator.
#'
#' @param generator Generator
#' @template len
#'
#' @examples
#' list_of(integer_(), len = 10L) |> show_example()
#' @template generator
#' @export
list_of <- function(generator, len = 1L) {
  vectorize(list(generator), len)
}
