#' List generator
#'
#' This will generate lists with contents corresponding
#' to the values generated by the input generators.
#'
#' @param ... Generators
#'
#' @template generator
#' @export
list_ <- \(...) {
  hedgehog::gen.with(list(...), as.list)
}

#' Variable length list generator
#'
#' This will generate lists with all values coming from the
#' single input generator.
#'
#' @template generator
#' @template len
#'
#' @template generator
#' @export
list_of <- \(generator, len = 1L) {
  vectorize(list(generator), len)
}
